language: bash
sudo: required
services:
- docker
script:
- |
  sudo apt-get update -qq &&\
  sudo apt-get install -qqy curl gcc python-dev python-setuptools apt-transport-https \
                            lsb-release openssh-client git bash jq sshpass openssh-client &&\
  sudo easy_install -U pip &&\
  sudo pip install -U crcmod python-dotenv pyyaml &&\
  openssl aes-256-cbc -K $encrypted_4fa8bbe6dd69_key -iv $encrypted_4fa8bbe6dd69_iv -in ./kamatera-secret.env.enc -out ./secret-kamatera.env -d &&\
  tests/run_all.sh
