{{ if .Values.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: noise
spec:
  completions: 10000
  parallelism: 2
  template:
    metadata:
      name: noise
    spec:
      nodeSelector:
        kamateranode: "true"
      containers:
      - name: pipelines
        image: orihoch/sk8s-pipelines@sha256:e89833818cef4f014b523ba1bedc074f060a78d2d16074459640149ef597b538
        command:
        - bash
        - "-c"
        - dpp run ./noise && dpp run ./amplify
        volumeMounts:
        - name: pipelines-data
          mountPath: /pipelines/data
          subPath: pipelines-data
      restartPolicy: Never
      volumes:
      - name: pipelines-data
        flexVolume:
          driver: rook.io/rook
          fsType: ceph
          options:
            fsName: noisefs
            clusterName: rook
{{ end }}
