{{ if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: kibana
spec:
  selector:
    app: kibana
  ports:
  - port: 5601
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kibana
spec:
  replicas: 1
  strategy: {type: Recreate}
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - image: kibana:5.3
        name: kibana
        ports:
        - containerPort: 5601
        env:
        - name: ELASTICSEARCH_URL
          value: http://elasticsearch:9200
        volumeMounts:
        - name: kibana-conf
          mountPath: /etc/kibana
      volumes:
      - name: kibana-conf
        configMap:
          name: kibana
{{ end }}
